# Generated by Django 3.0.7 on 2020-06-20 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wods', '0001_initial'),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('execution_date', models.DateField(default=datetime.date.today)),
                ('logging_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.Workout')),
            ],
        ),
    ]
