# Generated by Django 3.0.7 on 2020-06-10 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='execution_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
