# Generated by Django 3.0.7 on 2020-06-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20200610_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
