# Generated by Django 3.0.7 on 2020-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='kg',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
