# Generated by Django 3.0.7 on 2020-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='test_wod', max_length=200),
            preserve_default=False,
        ),
    ]
