# Generated by Django 3.0.7 on 2020-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
