# Generated by Django 3.0.6 on 2020-06-04 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
            preserve_default=False,
        ),
    ]
