# Generated by Django 3.0.6 on 2020-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0002_auto_20200604_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='workout',
            name='score',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workout',
            name='score_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(),
        ),
    ]
