# Generated by Django 3.0.7 on 2020-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0003_auto_20200621_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='kg',
            field=models.IntegerField(),
        ),
    ]
