# Generated by Django 3.0.7 on 2020-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0006_auto_20200621_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('FOR_TIME', 'For Time'), ('AMRAP', 'AMRAP'), ('EMOM', 'EMOM'), ('LIFTING', 'Weightlifting'), ('REPSCHEME', 'Rep Scheme')], default='FOR_TIME', max_length=9),
        ),
    ]
