# Generated by Django 3.0.7 on 2020-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodmovements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_unit',
            field=models.CharField(choices=[('METERS', 'm'), ('REPS', 'x'), ('WEIGHT', 'kg'), ('REPS_AND_WEIGHT', 'x @ kg'), ('CALORIES', 'cal')], default='REPS', max_length=20),
        ),
    ]
