# Generated by Django 3.0.7 on 2020-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodmovements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='has_reps',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='modality',
            field=models.CharField(choices=[('G', 'Gymnastics'), ('W', 'Weightlifting'), ('M', 'Monostructural')], default='G', max_length=1),
        ),
    ]
