# Generated by Django 3.0.6 on 2020-06-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
